name: noise
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2026.2.25
  - icu=78.2
  - libexpat=2.7.4
  - libffi=3.5.2
  - liblzma=5.8.2
  - libsqlite=3.51.2
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.1
  - packaging=26.0
  - pip=26.0.1
  - python=3.12.12
  - readline=8.3
  - setuptools=82.0.0
  - tk=8.6.13
  - tzdata=2025c
  - wheel=0.46.3
  - pip:
    - Kivy==2.3.1
    - PyAudio==0.2.14
    - corelog==0.0.22
    - numpy==2.4.2
    - typer==0.24.1

prefix: "/Volumes/Devo/Users/jago/miniforge3/envs/noise"
